name: nokken
description: "A medication tracking application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_local_notifications: ^18.0.1
  flutter_sticky_header: ^0.7.0
  path: ^1.8.3
  uuid: ^4.3.3
  intl: ^0.20.2
  timezone: 0.10.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true