name: Dart
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        
    - name: Install dependencies
      run: flutter pub get
       
    - name: Analyze project source
      run: flutter analyze

#     No tests have been created yet
#    - name: Run tests
#      run: flutter test
